### PR TITLE
fix: move breathing bar above hunger bar when Hunger is active

### PR DESCRIPTION
**Pull request by mohamedation**
added Breathing as optional dependency and created an override on Breathing bar position so it doesn't collide with Hunger bar.

### CODE REVIEW

**Review by Cervator — APPROVED** [review]
Same comment as https://github.com/Terasology/Thirst/pull/30 👍 

Although I'm curious how it varies with either modules solo activated vs both of them active - clashing overrides? 🤔

**Comment by mohamedation** [comment]
> Same comment as [Terasology/Thirst#30](https://github.com/Terasology/Thirst/pull/30) +1
> 
> Although I'm curious how it varies with either modules solo activated vs both of them active - clashing overrides? thinking

i tried them with both active and it works with no error, only warning
`[main] WARN  o.t.g.a.f.producer.UnloadedAssetData - Conflict - both module 'Hunger' and 'Thirst' override Breathing:Breathing, selecting 'Hunger'`

here is a screenshot for hunger only
Screenshot from 2021-10-25 20-26-53


and here are both
Screenshot from 2021-10-25 20-30-26-1

**Comment by Cervator** [comment]
Nice!

**Review by jdrueckert — APPROVED** [review]
Tests out nicely :+1:

**Pull request merged**
